/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAdmin: typeof import('./components/CRUD_Administradores/addAdmin.vue')['default']
    BtnComponent: typeof import('./components/btnComponent.vue')['default']
    ConfirmationComponent: typeof import('./components/confirmationComponent.vue')['default']
    EntidadeModifier: typeof import('./components/CRUD_Entidades/entidadeModifier.vue')['default']
    FileFieldComponent: typeof import('./components/fileFieldComponent.vue')['default']
    HoverBoxComponent: typeof import('./components/Hover-box/hoverBoxComponent.vue')['default']
    InfoEntidade: typeof import('./components/CRUD_Entidades/infoEntidade.vue')['default']
    ItemModifier: typeof import('./components/CRUD_Itens/itemModifier.vue')['default']
    LocationPickerComponent: typeof import('./components/locationPickerComponent.vue')['default']
    Navbar: typeof import('./components/Navbar/Navbar.vue')['default']
    OptionsAdmins: typeof import('./components/CRUD_Administradores/optionsAdmins.vue')['default']
    OptionsCRUD: typeof import('./components/optionsCRUD.vue')['default']
    OptionsItems: typeof import('./components/CRUD_Itens/optionsItems.vue')['default']
    PedidoCard: typeof import('./components/Pedidos/pedidoCard.vue')['default']
    PedidoModifier: typeof import('./components/Pedidos/pedidoModifier.vue')['default']
    PessoasTable: typeof import('./components/Pessoas/pessoasTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowAllPedidos: typeof import('./components/Pedidos/showAllPedidos.vue')['default']
    ShowPedidos: typeof import('./components/Pedidos/showPedidos.vue')['default']
    Snackbar: typeof import('./components/snackbar.vue')['default']
    TableAdmins: typeof import('./components/CRUD_Administradores/tableAdmins.vue')['default']
    TableEntidades: typeof import('./components/CRUD_Entidades/tableEntidades.vue')['default']
    TableItens: typeof import('./components/CRUD_Itens/tableItens.vue')['default']
    TextFieldComponent: typeof import('./components/textFieldComponent.vue')['default']
  }
}
