/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAdmin: typeof import('./components/CRUD_Administradores/addAdmin.vue')['default']
    AddFuncionario: typeof import('./components/CRUD_Administradores/addFuncionario.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ConfirmationComponent: typeof import('./components/confirmationComponent.vue')['default']
    CRUD_administradores: typeof import('./components/CRUD_administradores/CRUD_administradores.vue')['default']
    CRUD_funcionarios: typeof import('./components/CRUD_administradores/CRUD_funcionarios.vue')['default']
    HoverBoxComponent: typeof import('./components/Hover-box/hoverBoxComponent.vue')['default']
    Navbar: typeof import('./components/Navbar/Navbar.vue')['default']
    OptionsAdmins: typeof import('./components/CRUD_Administradores/optionsAdmins.vue')['default']
    OptionsFuncionarios: typeof import('./components/CRUD_Administradores/optionsFuncionarios.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/snackbar.vue')['default']
    Table: typeof import('./components/CRUD_Administradores/table.vue')['default']
  }
}
